// Command Trello-cli is a CLI + REPL for the Trello SDK,
// built on the boru engine. Positional arguments are joined into a
// single boru expression and evaluated; with no arguments, falls into
// a REPL. Generated by sdkgen go-cli target.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	"github.com/boru-lang/boru/eng/go/parser"
	sdk "github.com/voxgig-sdk/trello-sdk/go"
)

// prompt is the REPL prompt prefix (matches the SDK slug).
const prompt = "trello"

// entitiesHelp is the space-separated entity list shown by /help.
const entitiesHelp = "action action_reactions_summary admin application application_compliance associated_domain attachment batch board board_background board_plugin board_star bulk card card_check_item_state card_list check_item checklist claimable_organization custom_board_background custom_emoji custom_field custom_field_item custom_sticker email_position emoji enterpris enterpris_signup_url enterprise_admin enterprise_audit_log export export_download generate id_email_list id_label id_member label list member member_privacy members_voted membership most_recent new_billable_guest notification notification_channel_setting notification_list notification_member_creator notifications_channel_setting option org_invite_restrict organization pending_organization plugin plugin_data plugin_listing reaction read saved_search search show_sidebar show_sidebar_activity show_sidebar_board_action show_sidebar_member sticker tag token transferrable_organization trello_list webhook"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

// usage prints the CLI help (for --help / -h). No client or network setup.
func usage(out io.Writer) {
	fmt.Fprintf(out, "%s-cli — boru-driven CLI + REPL for the %s SDK\n\n", prompt, prompt)
	fmt.Fprintln(out, "Usage:")
	fmt.Fprintf(out, "  %s-cli [--help] [<boru expression>]\n\n", prompt)
	fmt.Fprintln(out, "With arguments, they are joined into a single boru expression and")
	fmt.Fprintln(out, "evaluated against the API. With no arguments, starts an interactive REPL.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Words:    list / load / update <query?> <entity>")
	fmt.Fprintln(out, "Entities:", entitiesHelp)
	fmt.Fprintln(out, "Env:      TRELLO_APIKEY (api key), TRELLO_BASE (base url override)")
	fmt.Fprintln(out, "REPL:     /help  /quit")
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	// --help / -h: print usage and exit before any config or network setup.
	for _, a := range args {
		if a == "--help" || a == "-h" {
			usage(out)
			return 0
		}
	}

	// Configure from the environment: TRELLO_APIKEY carries the API key and
	// TRELLO_BASE optionally overrides the API base URL (e.g. production).
	// Both injectable by a secrets vault. Unset -> nil config defaults.
	var opts map[string]any
	if apikey := os.Getenv("TRELLO_APIKEY"); apikey != "" {
		opts = map[string]any{"apikey": apikey}
	}
	if base := os.Getenv("TRELLO_BASE"); base != "" {
		if opts == nil {
			opts = map[string]any{}
		}
		opts["base"] = base
	}
	client := sdk.NewTrelloSDK(opts)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprintf(out, "%s> ", prompt)
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case "/quit", "/q", "/exit":
			return
		case "/help", "/h", "/?":
			fmt.Fprintln(out, "words:    list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities:", entitiesHelp)
			fmt.Fprintln(out, "meta:     /help  /quit")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}
