// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/trello-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.TrelloSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.TrelloSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.TrelloSDK, name string) (sdk.TrelloEntity, error) {
	switch strings.ToLower(name) {
	case "action":
		return client.Action(nil), nil
	case "action_reactions_summary":
		return client.ActionReactionsSummary(nil), nil
	case "admin":
		return client.Admin(nil), nil
	case "application":
		return client.Application(nil), nil
	case "application_compliance":
		return client.ApplicationCompliance(nil), nil
	case "associated_domain":
		return client.AssociatedDomain(nil), nil
	case "attachment":
		return client.Attachment(nil), nil
	case "batch":
		return client.Batch(nil), nil
	case "board":
		return client.Board(nil), nil
	case "board_background":
		return client.BoardBackground(nil), nil
	case "board_plugin":
		return client.BoardPlugin(nil), nil
	case "board_star":
		return client.BoardStar(nil), nil
	case "bulk":
		return client.Bulk(nil), nil
	case "card":
		return client.Card(nil), nil
	case "card_check_item_state":
		return client.CardCheckItemState(nil), nil
	case "card_list":
		return client.CardList(nil), nil
	case "check_item":
		return client.CheckItem(nil), nil
	case "checklist":
		return client.Checklist(nil), nil
	case "claimable_organization":
		return client.ClaimableOrganization(nil), nil
	case "custom_board_background":
		return client.CustomBoardBackground(nil), nil
	case "custom_emoji":
		return client.CustomEmoji(nil), nil
	case "custom_field":
		return client.CustomField(nil), nil
	case "custom_field_item":
		return client.CustomFieldItem(nil), nil
	case "custom_sticker":
		return client.CustomSticker(nil), nil
	case "email_position":
		return client.EmailPosition(nil), nil
	case "emoji":
		return client.Emoji(nil), nil
	case "enterpris":
		return client.Enterpris(nil), nil
	case "enterpris_signup_url":
		return client.EnterprisSignupUrl(nil), nil
	case "enterprise_admin":
		return client.EnterpriseAdmin(nil), nil
	case "enterprise_audit_log":
		return client.EnterpriseAuditLog(nil), nil
	case "export":
		return client.Export(nil), nil
	case "export_download":
		return client.ExportDownload(nil), nil
	case "generate":
		return client.Generate(nil), nil
	case "id_email_list":
		return client.IdEmailList(nil), nil
	case "id_label":
		return client.IdLabel(nil), nil
	case "id_member":
		return client.IdMember(nil), nil
	case "label":
		return client.Label(nil), nil
	case "list":
		return client.List(nil), nil
	case "member":
		return client.Member(nil), nil
	case "member_privacy":
		return client.MemberPrivacy(nil), nil
	case "members_voted":
		return client.MembersVoted(nil), nil
	case "membership":
		return client.Membership(nil), nil
	case "most_recent":
		return client.MostRecent(nil), nil
	case "new_billable_guest":
		return client.NewBillableGuest(nil), nil
	case "notification":
		return client.Notification(nil), nil
	case "notification_channel_setting":
		return client.NotificationChannelSetting(nil), nil
	case "notification_list":
		return client.NotificationList(nil), nil
	case "notification_member_creator":
		return client.NotificationMemberCreator(nil), nil
	case "notifications_channel_setting":
		return client.NotificationsChannelSetting(nil), nil
	case "option":
		return client.Option(nil), nil
	case "org_invite_restrict":
		return client.OrgInviteRestrict(nil), nil
	case "organization":
		return client.Organization(nil), nil
	case "pending_organization":
		return client.PendingOrganization(nil), nil
	case "plugin":
		return client.Plugin(nil), nil
	case "plugin_data":
		return client.PluginData(nil), nil
	case "plugin_listing":
		return client.PluginListing(nil), nil
	case "reaction":
		return client.Reaction(nil), nil
	case "read":
		return client.Read(nil), nil
	case "saved_search":
		return client.SavedSearch(nil), nil
	case "search":
		return client.Search(nil), nil
	case "show_sidebar":
		return client.ShowSidebar(nil), nil
	case "show_sidebar_activity":
		return client.ShowSidebarActivity(nil), nil
	case "show_sidebar_board_action":
		return client.ShowSidebarBoardAction(nil), nil
	case "show_sidebar_member":
		return client.ShowSidebarMember(nil), nil
	case "sticker":
		return client.Sticker(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "token":
		return client.Token(nil), nil
	case "transferrable_organization":
		return client.TransferrableOrganization(nil), nil
	case "trello_list":
		return client.TrelloList(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
